- name: Configure webserver with nginx
  hosts: all
  tasks:
    - name: Removing everything
      block:
        - name: Removing package
          yum:
            name: nginx
            state: absent
        - name: Removing files
          shell: rm -rf /etc/nginx/* && rm -rf /usr/share/nginx/*

    - name: install nginx
      yum:
        name:
          - nginx 
        state: latest

    - name: Configuring nginx
      lineinfile:
        path: /etc/nginx/nginx.conf
        line: 'include /etc/nginx/conf.d/*.conf;'
        state: present

    - name: Configuring nginx port
      lineinfile:
        path: /etc/nginx/nginx.conf
        regexp: 'listen       80;'
        line: 'listen       8080;'
        state: present

    - name: Configuring nginx port
      lineinfile:
        path: /etc/nginx/nginx.conf
        line: '        listen       [::]:80;'
        state: absent

#    - name: copy index.html
#      template: 
#        src: files/index.html.j2
#        dest: /usr/share/nginx/html/index.html
#        mode: 0644


    - name: restart nginx
      service: 
        name: nginx 
        state: restarted