- name: Configure webserver with nginx
  hosts: all
  tasks:
    - name: Removing everything
      block:
        - name: Removing package
          yum:
            name: nginx
            state: absent
        - name: Removing files
          shell: rm -rf /etc/nginx/* && rm -rf /usr/share/nginx/*

    - name: install nginx
      yum:
        name:
          - nginx 
        state: latest

    - name: copy nginx config file
      copy: 
        src: files/nginx.conf
        dest: /etc/nginx/sites-available/default

    - name: enable configuration
      file: 
        dest: /etc/nginx/sites-enabled/default
        src: /etc/nginx/sites-available/default
        state: link

    - name: copy index.html
      template: 
        src: files/index.html.j2
        dest: /usr/share/nginx/html/index.html mode=0644


    - name: restart nginx
      service: 
        name: nginx 
        state: restarted